connections {
    gw2-gw1 {
        version = 2
        local_addrs = 10.200.200.1
        remote_addrs = 10.100.100.1

        local {
            auth = psk
            id = 10.200.200.1
        }

        remote {
            auth = psk
            id = 10.100.100.1
        }

        children {
            lan-lan {
                local_ts = 172.16.2.0/24
                remote_ts = 172.16.1.0/24
                if_id_in = 1
                if_id_out = 1
                start_action = trap|start
            }
        }
    }
}

secrets {
    ike-gw1-gw2 {
        id-gw1 = 10.100.100.1
        id-gw2 = 10.200.200.1
        secret = "SECRET"
    }
}