frr version 8.4.4
frr defaults traditional
hostname p1
log syslog informational
service integrated-vtysh-config
!
ip router-id 10.255.0.1
!
interface ens19
 ip router isis CORE
 isis network point-to-point
 mpls enable
exit
!
interface ens20
 ip router isis CORE
 isis network point-to-point
 mpls enable
exit
!
interface ens21
 ip router isis CORE
 isis network point-to-point
exit
!
interface lo
 ip router isis CORE
 isis passive
exit
!
mpls ldp
 router-id 10.255.0.1
 !
 address-family ipv4
  discovery transport-address 10.255.0.1
  !
  interface ens19
  exit
  !
  interface ens20
  exit
  !
 exit-address-family
 !
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0000.0000.0002.00
 log-adjacency-changes
exit
!
end