# Temporary/work in progress
!
frr version 8.4.4
frr defaults traditional
hostname p1
log syslog informational
service integrated-vtysh-config
!
interface ens19
 ip router isis CORE
 isis network point-to-point
 mpls enable
exit
!
interface ens20
 ip router isis CORE
 isis network point-to-point
 mpls enable
exit
!
interface eth0
 mpls enable
exit
!
interface lo
 ip router isis CORE
 isis passive
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0000.0000.0002.00
 log-adjacency-changes
exit
!
end