!
frr version 8.4.4
frr defaults traditional
hostname RR1-FRR
log syslog informational
service integrated-vtysh-config
!
interface ens19
 ip router isis CORE
 isis network point-to-point
 mpls enable
exit
!
interface eth0
 mpls enable
exit
!
interface lo
 ip router isis CORE
 isis passive
exit
!
router bgp 65000
 bgp router-id 10.255.0.11
 no bgp default ipv4-unicast
 bgp cluster-id 10.255.0.11
 neighbor 10.255.0.101 remote-as 65000
 neighbor 10.255.0.101 update-source lo
 neighbor 10.255.0.102 remote-as 65000
 neighbor 10.255.0.102 update-source lo
 !
 address-family ipv4 vpn
  neighbor 10.255.0.101 activate
  neighbor 10.255.0.101 route-reflector-client
  neighbor 10.255.0.102 activate
  neighbor 10.255.0.102 route-reflector-client
 exit-address-family
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0000.0000.0011.00
 log-adjacency-changes
exit
!
end