network:
  version: 2
  renderer: networkd
  ethernets:
    ens19:
      dhcp4: false
      dhcp6: false
      addresses:
        - 10.0.0.5/31
    lo:
      addresses:
        - 127.0.0.1/8
        - ::1/128
        - 10.255.0.11/32