# Temporary/work in progress
set version 25.4R1.12
set system host-name pe1
set system root-authentication encrypted-password <SECRET>
set system root-authentication <SECRET>
set system services ssh
set system name-server 192.168.1.1
set interfaces ge-0/0/0 unit 0 family inet address 10.0.0.0/31
set interfaces ge-0/0/0 unit 0 family iso
set interfaces fxp0 unit 0 family inet address 192.168.1.201/24
set interfaces lo0 unit 0 family inet address 10.255.0.1/32
set interfaces lo0 unit 0 family iso
set routing-options router-id 10.255.0.1
set routing-options static route 0.0.0.0/0 next-hop 192.168.1.1
set protocols isis interface ge-0/0/0.0 point-to-point
set protocols isis interface lo0.0 passive
set protocols isis level 1 disable
set protocols isis net 49.0001.0000.0000.0001.00