set system host-name pe2
set routing-options router-id 10.255.0.102
set routing-options autonomous-system 65000
set interfaces ge-0/0/0 unit 0 family inet address 10.0.0.3/31
set interfaces ge-0/0/0 unit 0 family iso
set interfaces lo0 unit 0 family inet address 10.255.0.102/32
set interfaces lo0 unit 0 family iso address 49.0001.0000.0000.0102.00
set protocols isis interface ge-0/0/0.0 point-to-point
set protocols isis interface lo0.0 passive
set protocols mpls interface ge-0/0/0.0
set protocols ldp transport-address 10.255.0.102
set protocols ldp interface ge-0/0/0.0
set protocols bgp group RR type internal
set protocols bgp group RR local-address 10.255.0.102
set protocols bgp group RR family inet-vpn unicast
set protocols bgp group RR peer-as 65000
set protocols bgp group RR neighbor 10.255.0.11
set routing-instances CUST1 instance-type vrf
set routing-instances CUST1 route-distinguisher 65000:102
set routing-instances CUST1 vrf-target target:65000:100
set routing-instances CUST1 routing-options static route 172.16.2.0/24 discard